fos_rest:
    allowed_methods_listener:  true
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
