services:
    _defaults:
        public: true

    InstagramAPI\Instagram:
        class: InstagramAPI\Instagram

    test.App\Ig\ItemManager:
        alias: App\Ig\ItemManager
        public: true

    test.App\Ig\UserManager:
        alias: App\Ig\UserManager
        public: true
    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'
